### ISSUE TITLE
Cannot find it in HACS

### ISSUE THREAD

**Issue by n00bcodr** [JuanMTech/google-theme#1]
Searching google theme does not return anything in HACS themes

![image](https://user-images.githubusercontent.com/49611451/153798607-6d708a51-836d-4538-af25-889fc59e5961.png)

**Comment by flixlix** [comment]
Try adding it as a custom repo

**Comment by Dutchy-79** [comment]
Same here, not in hacs
![Screenshot_20220214-214114_Home Assistant](https://user-images.githubusercontent.com/22749572/153943191-b07844dd-2723-4f9f-a8ab-412052186880.png)

**Comment by sermayoral** [comment]
Please approve [this PR](https://github.com/hacs/default/pull/1246#pullrequestreview-883772204) in order to appears in HACS :-)

**Comment by Olum-hack** [comment]
I can't find it a few days ago.
But not it appears.

**Comment by Dutchy-79** [comment]
> I can't find it a few days ago. But not it appears.

It should be available now

**Comment by Dutchy-79** [comment]
> I can't find it a few days ago. But not it appears.

![Screenshot_20220221-230853_Home Assistant](https://user-images.githubusercontent.com/22749572/155031884-50a4cb4a-ea6d-4839-8aab-7455af9f1cca.png)
