### ISSUE TITLE
Various compatibility updates/tweaks needed as of 2022.9.0

### ISSUE THREAD

**Issue by krazos** [JuanMTech/google-theme#10]
Just a heads up that various updates are needed for compatibility with core-2022.9.0.  I will try to update with additional screenshots, etc. as soon as I can.  Thanks!

**Examples**:

**1) Area View under Settings > Areas & Zones**

_Default Theme_:

![image](https://user-images.githubusercontent.com/18428022/188958501-07c058fd-f23e-4704-b4f3-7285b7afeba5.png)

_Google Theme_:

![image](https://user-images.githubusercontent.com/18428022/188957256-d749e5d2-bbf1-451a-9288-f5b8bb9be408.png)

**2) Disabled Flag on New Automation and Script Editor**

_Default Theme_:

![image](https://user-images.githubusercontent.com/18428022/188958418-cdd651e1-bc7d-42e2-b867-76ea324d27dc.png)

_Google Theme_:

![image](https://user-images.githubusercontent.com/18428022/188958214-402355a7-45b3-42ee-a78a-22ed1f4cf7b0.png)

**Comment by JuanMTech** [comment]
Fixed on latest version.
