### ISSUE TITLE
Graphical issues as of HA 2022.11 (incorrect border around cards)

### ISSUE THREAD

**Issue by pacjo** [JuanMTech/google-theme#11]
As of home assistant 2022.11 update:

> The default dashboard theme has been adjusted to move a little closer to the new Material Design 3 guidelines. 
> **Borders around cards are now outlined (instead of having a shadow), and corners are a little more rounded.**

this creates issues with vertical and horizontal stacks, while using `in_card` property from home assistant canary (https://github.com/jcwillox/lovelace-canary)

result (google theme):
![theme1](https://user-images.githubusercontent.com/56438628/200076038-3c8082e6-bbb0-464f-bca0-8b19f16cfffa.png)
![theme2](https://user-images.githubusercontent.com/56438628/200076041-699888f5-b4de-487a-884d-5fc1673d3204.png)

**Comment by iMiMx** [comment]
https://github.com/jcwillox/lovelace-canary/issues/21

**Comment by JuanMTech** [comment]
Fixed
