### ISSUE TITLE
Yellow buttons after 2022.12 update

### ISSUE THREAD

**Issue by PilaScat** [JuanMTech/google-theme#14]
![image](https://user-images.githubusercontent.com/12989749/207447979-364808ed-5212-4473-8509-b9cac4b69c50.png)

**Comment by cturra** [comment]
you can find the blog post around the entity state color changes made in 2022.12 here:

 * https://developers.home-assistant.io/blog/2022/12/07/entity-color-changes

**Comment by PilaScat** [comment]
where i could change the primary color for your theme?
Can I set this in the configuration.yaml?

**Comment by cdemi** [comment]
In addition, the Alarm button is Green when Armed Away now. It should be red.

**Comment by BunpGhost** [comment]
I'm also having this issue.

And I'm using the isolated versions of light and Dark, because I need to manually change them because my tablet is old and doesn't support dark mode :) 
Is it possible to fix this in all 3 themes please?
Or tell us how to fix it?
Thanks

**Comment by JuanMTech** [comment]
Can't replicate the issue.

**Comment by cturra** [comment]
https://github.com/home-assistant/frontend/pull/14672/commits/1ad3fa4b5bbc4a28d3efa0042d4cc81db066d57e

**Comment by PilaScat** [comment]
> [home-assistant/frontend@1ad3fa4](https://github.com/home-assistant/frontend/commit/1ad3fa4b5bbc4a28d3efa0042d4cc81db066d57e)
How to change this easly?

**Comment by BunpGhost** [comment]
> Can't replicate the issue.

Well.. I just created a normal button and this is the result, when active, it shows yellow!
![image](https://user-images.githubusercontent.com/25492163/212310348-75bdd22d-d901-47b9-87c3-e6a83abd10d6.png)

Does anyone know how to fix this?

**Comment by JuanMTech** [comment]
Fixed on v.14

**Comment by cdemi** [comment]
Thanks a lot. I know you do this for free and in your spare time so I appreciate you taking the time to fix this

**Comment by BunpGhost** [comment]
> Fixed on v.14

Thanks for this. 
I can see that the google and ios themes are ok. However, can you also fix the individual Light and Dark repositories as well?
My devices don't have dark mode so I have to run an automation that changes the themes based on the sun and for that I need to have separate themes...
Thank you in advance.
