### ISSUE TITLE
Blue icons in UI generated dashboard

### ISSUE THREAD

**Issue by mat4444** [JuanMTech/google-theme#15]
Hello,
I have recently transitioned from a yaml dashboard to a UI generated dashboard.
When applying the dark Google theme, all the icons look blue in the UI generated dashboard, instead of grey as expected.

YAML dashboard:
![YAML](https://user-images.githubusercontent.com/53400792/209169987-41ce90f9-b3be-4273-bb87-dac9016f458d.png)

 Identical dashboard, created with the UI:
![UI](https://user-images.githubusercontent.com/53400792/209170087-cb6759c6-6ec1-43fc-9588-38aa2b9e15bf.png)

This behavior only happens with the dark mode, not the light mode.
I have the latest HA and theme versions. HA : 2022.12.8, theme V1.2
I have already completely deleted the theme, restarted HA, reinstalled the theme. I followed the instructions to apply the theme to the letter, even deleted the cache etc., but I still have the issue. I have tested it on 3 different devices: same behavior with a browser (Firefox and Chrome) and the Android app.
Has anyone noticed that ?

Thanks!

**Comment by JuanMTech** [comment]
Fixed on latest version
