### ISSUE TITLE
Invisible radio buttons

### ISSUE THREAD

**Issue by mat4444** [JuanMTech/google-theme#16]
Hello,
In dark mode, the unchecked radio buttons are not visible as shown below:

![Radio button](https://user-images.githubusercontent.com/53400792/209176918-ff881cb4-92f2-4800-8271-9d08e25d5108.png)

Whereas we clearly see them with the default theme:
![Radio button 2](https://user-images.githubusercontent.com/53400792/209176976-968c5a42-aea6-4aa1-9b1b-651740cd2f03.png)

Any chance it can be fixed ?

**Comment by JuanMTech** [comment]
Fixed on latest version
