### ISSUE TITLE
Has this theme been removed from HACS?

### ISSUE THREAD

**Issue by luixal** [JuanMTech/google-theme#22]
Hi,

Since some time ago, HACS is showing and alert about this theme's repo being archived and it no longer allows you to install the theme.

At least you have to do some workarounds to get it installed.

Any idea on this?

Thanks!

**Comment by r7o3gko8** [comment]
Hi @luixal,
You are probably running my version of this theme (https://github.com/digitaljamie/google-theme), which was created to fix issues with the original version. These issues have now been fixed so the repo is archived.
I'd recommend switching back to JuanMTech's version. In HACS, search for 'google-theme' and install it there.

**Comment by luixal** [comment]
Sure, my problem was I hadn't remove the custom repo from my HACS config.

Thanks!
