### ISSUE TITLE
Theme not auto swtiching light <> dark

### ISSUE THREAD

**Issue by lozzamatron** [JuanMTech/google-theme#5]
I've installed through HACS, selected 'Google Theme' under profile across various devices - iPad app, Android App, Chrome Browser etc. selected the 'auto' radio button, and the theme does not automatically swtich from light > dark at night.

In my log, there are a couple of orange warning lines:
22-03-01 19:18:58 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-03-01 19:18:58 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)

**Comment by blakeseufert** [comment]
I have a similar problem where i set an automation to select light or dark and it has no effect. My theme is set to backend-selected

**Comment by JuanMTech** [comment]
After you run the steps to set up the theme, you will need to select Backend-selected as the theme.

**Comment by lozzamatron** [comment]
OK this is confusing as in the install it says to select 'Google Theme' and you are saying use 'Backend Selected'... If I use backend selected, how do I get it to use the new Google Theme?

**Comment by DrSpaldo** [comment]
Likewise, I am confused. How do you make it switch between dark/light modes when it is night time?
