### ISSUE TITLE
State Color in dark mode incorrect

### ISSUE THREAD

**Issue by digitaljamie** [JuanMTech/google-theme#6]
I have some entity cards using state_color: true, which should mean only the entities currently turned on will be lit up.
However, using this theme in dark mode, the devices turned off are blue, and the devices turned on are grey. This should be the opposite.
It works correctly in light mode.
It also seems to work correctly in dark mode in the card configuration menu, but not when viewing on the dashboard
![image](https://user-images.githubusercontent.com/100302760/165065792-61169d5f-0246-4115-8b6e-2a298ab5e211.png)

**Comment by kineticscreen** [comment]
Did this problem only just start with one of the most recent HA updates? I'm only just noticing it.

**Comment by JuanMTech** [comment]
It was set up like that on purpose. You can change it in the theme file if you would like.

**Comment by kineticscreen** [comment]
@digitaljamie is your fork of this theme going to correct this? Very strange choice.

**Comment by digitaljamie** [comment]
@kineticscreen My fork has fixed this (it's only switching the colour values in 2 lines round).
The negative to this is that entities without 'state_color: true' enabled or without on/off states will show in the gray colour. I can't see a way without this happening.

**Comment by kineticscreen** [comment]
@digitaljamie sounds good - and that's how the theme used to work anyway? I think that's preferable, it's too confusing otherwise for the colour blue to essentially have different meanings for different devices.
(also plenty of custom cards had grey buttons / icons anyway, so it was all over the place with this change).
Cheers!
