### ISSUE TITLE
Difference in color on/off between light/dark themes

### ISSUE THREAD

**Issue by fernandolcardoso** [JuanMTech/google-theme#9]
In light theme, the icon is displayed in the correct color, representing the on/off state

![image](https://user-images.githubusercontent.com/16019127/167973344-a9564e59-cddc-4c39-b440-8df36213b9d2.png)

But in the dark theme, the icon is displayed in reverse, causing confusion if the state is on or off.

![image](https://user-images.githubusercontent.com/16019127/167973378-4ba615df-439f-48d3-be64-688bce7dddb2.png)

I suggest you fix the dark theme to show the icon colors as per the light theme colors.

**Comment by JuanMTech** [comment]
I checked this on my end and its working correctly.

**Comment by digitaljamie** [comment]
This is the same issue I reported (#6 ), where @JuanMTech said 'It was set up like that on purpose'.
@fernandolcardoso I fixed the issue in [my fork](https://github.com/digitaljamie/google-theme). It only changes 2 lines of YAML

**Comment by bokub** [comment]
I have the same problem 😢
